travis:
  secure:
    BINSTAR_TOKEN: T5XxOs5rcHWSvdHzZAWA98Qc0n0AerfuNWPP+Ly74FhcEUpowwdB3CtqORAUDRJNqU5r+RJ2s7gkdKVXkWSYkmZEwujVOgbC/GqOKBv0JMuDpk2DlBzZtqdHYrHlH71qAQF+ObvNT7/u2BPzGjrIZaCUgolM4havZWrDOzWrxuNcoVMuXaX49PJUw/csO6Vq1ZxIguVBn7zE/ekqvK6DeDq2j4lLaN7LDvOHW1pj7/MOCF7SkOqNduFWaD9GlxAU4nbePJNrgdEU+W+dJBZXfISxaY6ucJqzvXhyG5Zsv88c2t+KMkJd0IkaoNxme56ouxwbpW1sPAF77iEDVJf01GA3wFfTYHnXrdih1plZ38Xg8w1MDbYDi8Ur6v+sg8PdvUBmDD6Naks7nq9XIOIsXze648sDDNa0DCkbuH7i98UT1jDVGRwtcULEcJDinyV22g1a2hZOM8LOteKMKQx+YQRDexStg8qNb3Z2N3YEzYxZF29Mf6q8KBZt+mtMeMG9W0zeq64cJ3kl/zVQL51Fd/95/Ew6ifdu3szlGe84wMTsyFEJockgkpJpodUHUpuyeB83OXHzgVa7dSmSF3fIDp9QwSfywyAy4fQ7Lv2Xbun660L55K9q4VXL3aue5DoJUi4AF8tK+1bWWTtOsIDRH4F//zCz2nTmY5PrRUpbMnk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
